# Generated by Django 5.1.4 on 2025-01-02 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Gpatient", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="patient",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="revealrecords",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
