# Generated by Django 5.1.4 on 2025-01-03 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Gpatient", "0002_alter_appointment_id_alter_doctor_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="department",
            old_name="depID",
            new_name="DepId",
        ),
        migrations.RemoveField(
            model_name="doctor",
            name="special",
        ),
        migrations.AlterField(
            model_name="appointment",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="revealrecords",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
