# Generated by Django 5.1.4 on 2025-02-10 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Gpatient", "0004_rename_gnere_patient_gender_patient_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Confirmed", "Confirmed"),
                    ("Cancelled", "Cancelled"),
                ],
                default="Pending",
                max_length=10,
            ),
        ),
    ]
